silinternational/idp-id-sync

- application/common/sync/Synchronizer.php
- features/bootstrap/SyncContext.php
- features/sync.feature
Well, that was easier than expected.  :-)
> Add incremental sync

- application/common/components/adapters/InsiteIdStore.php
- dockerbuild/idsync-cron
See commit messages for details.
> Small tweaks

- application/common/components/IdBrokerBase.php
- application/common/components/adapters/IdpIdBroker.php
- application/common/components/adapters/fakes/FakeIdBroker.php
- application/common/components/notify/ConsoleNotifier.php
- application/common/components/notify/EmailServiceNotifier.php
- application/common/components/notify/NullNotifier.php
- application/common/config/main.php
- application/common/interfaces/IdBrokerInterface.php
- application/common/interfaces/NotifierInterface.php
- application/composer.json
- application/composer.lock
- application/features/bootstrap/IdpIdBrokerIntegrationContext.php
- application/frontend/controllers/SiteController.php
- codeship-services.yml
- docker-compose.yml
- local.env.dist
This updates the ID Sync's "status check" URL to also check:
- that ID Broker's status check returns a good value
- that the Email Service (if in use) also returns a good status check value
> Improve status check

- application/common/config/main.php
- application/composer.json
- application/composer.lock
- codeship-services.yml
- local.env.dist
This also updates the composer dependencies.
> Refactor logging config

- Vagrantfile
- application/composer.json
- application/composer.lock
- application/features/bootstrap/IdStoreIntegrationContextBase.php
Aside from small tweaks, this is to get ID Sync to be rebuilt on updated base docker images, which should resolve the `pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory` error we're seeing in the logs.
> Small bugfixes

- application/composer.json
- application/composer.lock
This adds support for manager's and spouse's email address fields
> Update ID Broker Client (and other dependencies)

- CHANGELOG.md
- application/common/components/adapters/GoogleSheetsIdStore.php
- application/common/components/adapters/WorkdayIdStore.php
- application/common/config/main.php
- application/common/models/User.php
- application/composer.json
- application/composer.lock
- application/run.sh
- codeship-services.yml
- local.env.dist
Added `groups` and `personal_email` attributes
Also:
- made `EMAIL_SERVICE_` vars optional if `ALERTS_EMAIL` and `NOTIFIER_EMAIL_TO` are both empty.
- revised startup script to watch for termination signal for a clean, quick shutdown
> Add groups attribute and personal_email attribute

- application/common/components/adapters/SagePeopleIdStore.php
- application/composer.json
- application/composer.lock
- docker-compose.yml
Moved array collapse "helper" method to a separate library
> Use dot notation library

- application/common/config/main.php
- application/composer.lock
- application/features/behat.yml
- application/frontend/config/main.php
Configure Yii logging to immediately output log messages, rather than cache them up. Prevents messages from being lost if the container crashes (e.g. out of memory).
> no log delay

- Dockerfile
- LICENSE
- application/composer.json
- application/composer.lock
- application/versions.json
- codeship-services.yml
- docker-compose.yml
- Upgrade to PHP 7.4
- Update year in license copyright
- Update dependencies
- Switch from fxp's composer-asset-plugin to asset-packagist
> Upgrade to PHP 7.4

- CHANGELOG.md
- Correct the "env" value in console logs
> Release 4.1.3

- CHANGELOG.md
- LICENSE
- README.md
- application/common/components/IdStoreBase.php
- application/common/components/adapters/GoogleSheetsIdStore.php
- application/common/components/adapters/SagePeopleIdStore.php
- application/common/components/adapters/WorkdayIdStore.php
- application/common/components/adapters/fakes/FakeIdStore.php
- application/common/components/notify/FakeEmailNotifier.php
- application/common/models/User.php
- application/features/behat.yml
- application/features/bootstrap/NotificationContext.php
- application/features/bootstrap/SyncContext.php
- application/features/notification.feature
- application/features/sync.feature
- application/features/user.feature
- local.env.dist
At a good point for review, so here goes. This contains some renaming to support additional notification capability coming soon. Also added some test capability and two new User fields, `hr_contact_name` and `hr_contact_email`, that will only be used internally and not sent to ID Broker.
> groundwork for new notification feature

- CHANGELOG.md
- application/frontend/controllers/SiteController.php
- remove redundant error log entry in /site/system-status handler
> Release 4.2.2 - error cleanup

- application/common/sync/Synchronizer.php
[IDP-601](https://itse.youtrack.cloud/issue/IDP-601) Avoid/handle email-sending rate limit issue for our IDPs
> Create one error message for all update-failed users.

- application/common/config/main.php
- application/composer.json
- application/composer.lock
- application/dependencies.json
- local.env.dist
- Add Sentry logging to potentially stop using the IDP's email-service for email alerts.
> add Sentry logging

- .github/pull_request_template.md
- application/common/config/main.php
- dockerbuild/idsync-cron
- New pull request template.
- Removed an unused "use" statement.
> add a pull request template; remove unused "use" statement

- .gitignore
- application/common/config/main.php
- application/composer.json
- application/composer.lock
- application/console/controllers/BatchController.php
- local.env.dist
- Use Sentry inProgress monitor check-in
---
> Release 5.1.0 - Use Sentry monitor service

- application/common/components/adapters/IdpIdBroker.php
- Fix instantiation of `Exception` in IdpIdBroker->listUsers()
* The 2nd parameter should be the code (as an `int`). We had left that out.
---
> Fix instantiation of Exception in IdpIdBroker->listUsers()

- codeship-services.yml
- Update to direct usage of mariadb:10 image
> Update codeship-services to use mariadb:10 directly

- application/common/components/Monitor.php
- application/common/config/main.php
- application/console/controllers/BatchController.php
- local.env.dist
- Added a new monitoring option that uses a simple http request
---
> Release 5.2.0 -- new monitoring option

- .github/pull_request_template.md
- .github/workflows/test-and-publish.yml
- Dockerfile
- application/common/components/Monitor.php
- application/common/config/main.php
- application/console/controllers/BatchController.php
- local.env.dist
- New option to use AppConfig to supply environment variable values
- Get the release tag from GitHub for use in the Sentry release string
- Use org-level variable and GitHub variable to build the Docker image name
> Release 5.3.0 -- AppConfig

- .github/workflows/test-and-publish.yml
**Added**
Added step to push the docker image to Github Container Registry
> Pushing Docker Image to GHCR.io

- application/composer.json
- application/composer.lock
- application/dependencies.json
[IDP-1507](https://support.gtis.sil.org/issue/IDP-1507) idp-id-sync alert #22: CVE-2024-58136
---
- Remove requirement of fake-bower-assets dependency
- Update dependencies
- Fix CVE-2024-58136
---
> Release 5.6.1 - Update insecure dependency
