application/common/models/User.php, application/features/behat.yml, application/features/bootstrap/UserContext.php, application/features/user.feature
Our ID Store is apparently returning `'locked': 'false'` rather than `'no'`. This helps handle that.
=> Convert locked to 'yes' or 'no'

application/common/config/main.php, local.env.dist
This is for the HR notification emails send by ID Sync (with the list of accounts that lack an email address).
=> Prefer IdP display name

application/common/config/main.php, application/common/sync/Synchronizer.php, application/common/traits/SyncProvider.php, application/features/behat.yml, application/features/bootstrap/SafetyCutoffContext.php, application/features/bootstrap/SyncContext.php, application/features/safetyCutoff.feature, application/features/sync.feature
This puts the safety cutoff in place for preventing too many deactivations, updates, or additions.
For a full sync, the cutoff is applied to each operation (create and deactivate) separately. Since we aren't comparing values to know whether a user found in both the ID Broker and the ID Store actually needs to be updated, we can't really limit the number of updates that a full sync does (since all users found in both places will be updated).
For an incremental sync, we're simply given a list of Employee IDs. If that total is more than our safety cutoff, we abort (rather than tallying up separate counts for each type of operation).
=> Prevent ID Sync from changing too many users at a time

application/common/components/IdStoreBase.php, application/common/components/adapters/WorkdayIdStore.php, application/common/models/User.php, application/features/behat.yml, application/features/bootstrap/UserContext.php, application/features/bootstrap/WorkdayIntegrationContext.php, application/features/id-store-integration.feature, application/features/user.feature, local.env.dist
**Added:**
- ID Store adapter for Workday
**Fixed:**
- Treat `'0'` and `0` as `'no'` and treat `'1'` and `1` as `'yes'` (as values for `locked` and `require_mfa`)
- Ignore unexpected ID Store fields, rather than crashing
=> Workday ID Store adapter

CHANGELOG.md, application/common/sync/Synchronizer.php, application/run-full-batch.sh, application/run-incremental-batch.sh
This is to help clarify which HR system ID Sync is pulling data from, which can be useful when transitioning from an old HR system to a new one.
=> Specify in log messages which ID Store adapter was used

CHANGELOG.md, application/common/sync/Synchronizer.php
- Stop limiting the number of changes (in a single sync) to an essentially-empty
broker (e.g. when populating it for the first time)
=> Ease initial sync

application/common/components/clients/GoogleSheetsClient.php
When reading data from Google Sheets, handle empty cells so that an incomplete line doesn't abort the sync. I saw this happen when someone started a new line with only an id, which quite effectively disabled all sync activity.
=> add null check to be resilient against incomplete rows

Makefile, application/check-psr2.sh, application/common/components/adapters/WorkdayIdStore.php, application/phpunit.xml, application/run-tests.sh, application/tests/WorkdayIdStoreTest.php, local.env.dist
`groupsFields` is a comma-delimited list of Workday fields used to create the 'groups' field on the ID Broker. The content of each field is converted from space-delimited to comma-delimited and merged together to form the 'groups' field.
=> new Workday groups config option

application/yii
The frontend [was properly setting this](https://github.com/silinternational/idp-id-sync/blob/27fc73f331e0ee57b75400d6c48e136283dbe310/application/frontend/web/index.php#L5), but for console executions (like the cron-based sync actions), this was always defaulting to "dev", even in production environments.
I'm not using our `Sil\PhpEnv\Env` class here because the composer autoloader isn't pulled in until after this line, and I don't know the effects on Yii of me changing that here.
=> Set cli's YII_ENV based on APP_ENV env. variable

CHANGELOG.md, application/common/components/notify/ConsoleNotifier.php, application/common/components/notify/EmailServiceNotifier.php, application/common/components/notify/FakeEmailNotifier.php, application/common/components/notify/NullNotifier.php, application/common/config/main.php, application/common/interfaces/NotifierInterface.php, application/common/mail/new-user.html.php, application/common/mail/new-user.text.php, application/common/sync/Synchronizer.php, application/common/traits/SyncProvider.php, application/features/bootstrap/NotificationContext.php, application/features/bootstrap/SyncContext.php, application/features/notification.feature, local.env.dist
Following is HR's request:
> An OU HR contact needs to receive a notification email when one of their staff gets a new SIL IdP account. 
>
> In some OUs, the HR contact will forward the email to their OU IT, who will use this information to verify with Sherlock that the user has properly set up their 2SV, password, etc.
>
> The notification email can be similar to the kind of email that HR receives when a Google account is created for one of their staff.
>
> Two new columns will be added to the [_Workday_] Integration report so that the SIL IdP integration can know who the appropriate HR contact is (based on the HR admin of the staff's Company of assignment).
>
> - HR Contact Name
> - HR Contact Email
>
> These columns would supply the HR contact name and email address for the …
=> send new user notification email if enabled

CHANGELOG.md, Makefile, application/common/components/notify/EmailServiceNotifier.php, application/common/config/main.php, application/common/mail/new-user.html.php, application/common/mail/new-user.text.php, application/run.sh, local.env.dist
- Improved the new-user email template to be more friendly
- Don't destroy all the Docker infrastructure on the user's dev machine in 'make clean'.
- Made email configuration required.
- Removed Xdebug since it is no longer readily available in the base image.
=> improved new-user email template

application/common/sync/Synchronizer.php, application/console/controllers/BatchController.php
Am I seeing this right, that every `error` log also gets sent as an email to the 
`$alertsEmail = Env::get('ALERTS_EMAIL');` config?
This is in relation to 
https://trello.com/c/M6elHO0Z/449-email-alert-for-idp-sync-failure
=> If syncAll() throws an exception, make sure it gets logged and emailed

application/common/sync/Synchronizer.php
- Improve error log by catching and adding to an ID Store exception.
Example error message before this change:
```
{
"app_env": "staging",
"idp_name": "appsdev",
"level": "error",
"category": "application",
"message": [
"There was an error with the sync process. Code: 429, Message: {",
"  \"error\": {",
"    \"code\": 429,",
"    \"message\": \"Resource has been exhausted (e.g. check quota).\",",
"    \"errors\": [",
"      {",
"        \"message\": \"Resource has been exhausted (e.g. check quota).\",",
"        \"domain\": \"global\",",
"        \"reason\": \"rateLimitExceeded\"",
"      }",
"    ],",
"    \"status\": \"RESOURCE_EXHAUSTED\"",
"  }",
"}",
""
]
}
```
=> add a bit of context to ID Store exception

.github/workflows/test-and-publish.yml, Makefile, README.md, actions-services.yml, application/composer.lock, application/dependencies.json, docker-compose.yml
- Dependency updates, including yii2 update for CVE-2024-4990 ([IDP-1138](https://itse.youtrack.cloud/issue/IDP-1138))
=> Release 5.4.1 -- dependency updates

application/common/components/adapters/IdpIdBroker.php, application/common/components/adapters/fakes/FakeIdBroker.php, application/common/interfaces/IdBrokerInterface.php, application/features/bootstrap/IdpIdBrokerIntegrationContext.php, application/features/idp-id-broker-integration.feature
- Removed dead code related to activating users and setting passwords
---
=> remove dead code related to activating users and setting passwords

.github/CODEOWNERS, .github/pull_request_template.md, .github/workflows/test-and-publish.yml, Makefile, actions-services.yml, application/features/bootstrap/IdpIdBrokerIntegrationContext.php
- Also push a major-version tag to image repos
- Add an assertion in `anActiveUserExists` to ensure the test user is active.
=> Release 5.4.4 -- Also push a {major} version tag (e.g. 6)

Dockerfile, README.md, application/run.sh
- Added Parameter Store as an alternative to AppConfig
---
=> Release 5.5.0 -- add Parameter Store as an alternative to AppConfig

Dockerfile
- Removed config-shim from Dockerfile to use the version in the silintl/php8 base image
=> Release 5.5.1 -- use config-shim from base image

application/common/config/main.php, application/run.sh
- Include app version in log messages
---
=> Release 3.5.2 -- log the app version

Dockerfile, application/composer.json, application/composer.lock, application/dependencies.json, application/features/bootstrap/NotificationContext.php, docker-compose.yml
- Update to php 8.3
- Upgrade dependencies
=> Release 5.6.0 - Update to PHP 8.3
